services:
  mysql:
    image: 'mysql:8.1'
    environment:
      - 'MYSQL_DATABASE=picpay'
      - 'MYSQL_PASSWORD=123456'
      - 'MYSQL_ROOT_PASSWORD=142536'
      - 'MYSQL_USER=admin'
    ports:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
