spring:
  application:
    name: picpay
  flyway:
    baseline-on-migrate: true
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/picpay
    username: admin
    password: 123456
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
client:
  notification-service: https://run.mocky.io/v3/5ca10f49-e528-4d7b-9844-1c92e412c4b2
  authorization-service: https://run.mocky.io/v3/42905a90-5760-4143-8690-7401f84c41e6