spring:
  application:
    name: picpay
  flyway:
    baseline-on-migrate: true
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/picpay
    username: admin
    password: 123456
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect